/**
 * Fixed service catalog for ALPIERCING (single-store).
 * Setmore-style list grouped by the categories shown at the physical stand:
 * NOSTRIL, HELIX, NAVEL and TITANIO (premium ASTM F-136 titanium line).
 * Money is stored as integer cents (constitution Principle IV).
 */
export type PiercingServiceCategory = "NOSTRIL" | "HELIX" | "NAVEL" | "TITANIO";

export interface PiercingService {
  id: string;
  name: string;
  category: PiercingServiceCategory;
  priceCents: number;
  durationMinutes: number;
  description: string;
  requiresDeposit: boolean;
  /** Public visibility flag. Inactive services are hidden from the booking menu. */
  active: boolean;
}

/** Creation input — the `id` is generated by the data source (DB uuid / crypto.randomUUID). */
export interface NewServiceInput {
  name: string;
  category: PiercingServiceCategory;
  priceCents: number;
  durationMinutes: number;
  description: string;
  requiresDeposit: boolean;
}

export interface PiercingServiceCategoryInfo {
  id: PiercingServiceCategory;
  label: string;
  description: string;
}

export const PIERCING_SERVICE_CATEGORIES: PiercingServiceCategoryInfo[] = [
  { id: "NOSTRIL", label: "NOSTRIL", description: "Piercing de Nariz" },
  { id: "HELIX", label: "HELIX", description: "Cartílago de Oreja" },
  { id: "NAVEL", label: "NAVEL", description: "Piercing de Ombligo" },
  {
    id: "TITANIO",
    label: "TITANIO",
    description: "Perforación + Joyería Premium Titanio ASTM F-136",
  },
];

export const PIERCING_SERVICES: PiercingService[] = [
  {
    id: "00000000-0000-4000-8000-000000000001",
    name: "Nostril Piercing",
    category: "NOSTRIL",
    priceCents: 2500, // $25.00
    durationMinutes: 30,
    description: "Perforación lateral de la nariz con joya inicial de titanio.",
    requiresDeposit: true,
    active: true,
  },
  {
    id: "00000000-0000-4000-8000-000000000002",
    name: "Septum Piercing",
    category: "NOSTRIL",
    priceCents: 3000, // $30.00
    durationMinutes: 30,
    description: "Perforación del tabique nasal con argolla o herradura de titanio.",
    requiresDeposit: true,
    active: true,
  },
  {
    id: "00000000-0000-4000-8000-000000000003",
    name: "Helix Piercing",
    category: "HELIX",
    priceCents: 2500, // $25.00
    durationMinutes: 30,
    description: "Perforación en el cartílago superior de la oreja.",
    requiresDeposit: true,
    active: true,
  },
  {
    id: "00000000-0000-4000-8000-000000000004",
    name: "Conch Piercing",
    category: "HELIX",
    priceCents: 3000, // $30.00
    durationMinutes: 30,
    description: "Perforación en la concha del cartílago auricular con joya de titanio.",
    requiresDeposit: true,
    active: true,
  },
  {
    id: "00000000-0000-4000-8000-000000000005",
    name: "Navel Piercing",
    category: "NAVEL",
    priceCents: 3200, // $32.00
    durationMinutes: 35,
    description: "Perforación del ombligo con navel ring de titanio.",
    requiresDeposit: true,
    active: true,
  },
  {
    id: "00000000-0000-4000-8000-000000000006",
    name: "Perforación Premium + Titanio ASTM F-136",
    category: "TITANIO",
    priceCents: 4500, // $45.00
    durationMinutes: 45,
    description:
      "Perforación con joyería premium de titanio ASTM F-136 (grado implante) y zirconia.",
    requiresDeposit: true,
    active: true,
  },
];
