/**
 * Shared domain types and the unified data-store contract for the hybrid
 * data layer (demo localStorage adapter vs production Supabase adapter).
 * Integer cents end-to-end (constitution Principle IV); no `any`.
 */
import type { NewServiceInput, PiercingService } from "../data/services";
import type { ProductCategory } from "./content";

export type BookingStatus = "PENDING" | "CONFIRMED" | "CANCELLED";
export type DataMode = "demo" | "production";

export interface Booking {
  id: string;
  createdAt: string; // ISO
  clientName: string;
  clientWhatsapp: string;
  /**
   * UUID of the referenced service, or `null` once that service was deleted
   * (FK `ON DELETE SET NULL`). `serviceName`/`priceCents` keep the snapshot.
   */
  serviceId: string | null;
  serviceName: string;
  priceCents: number; // integer cents, ≥ 0
  depositCents: number; // Math.round(priceCents / 2)
  date: string; // local ISO yyyy-mm-dd
  timeSlot: string; // HH:mm
  status: BookingStatus;
  notes?: string;
}

export interface ProductRecord {
  id: string;
  name: string;
  category: ProductCategory;
  priceCents: number; // integer cents, ≥ 0
  stock: number; // ≥ 0
  image: string;
  published: boolean; // false → hidden from public catalog
}

export interface NewBookingInput {
  clientName: string;
  clientWhatsapp: string;
  serviceId: string;
  serviceName: string;
  priceCents: number;
  date: string;
  timeSlot: string;
  notes?: string;
}

export interface NewProductInput {
  name: string;
  category: ProductCategory;
  priceCents: number;
  stock: number;
  image: string;
}

/** Manual unavailability block created by the operator (feature 006). */
export interface TimeBlock {
  id: string;
  date: string; // local ISO yyyy-mm-dd
  timeSlot: string; // HH:mm within the calendar window
  durationMinutes: number; // 15 | 30 | 60 | 90 | 120
  label: string; // non-empty (e.g. "Almuerzo", "Personal")
}

export interface NewBlockInput {
  date: string;
  timeSlot: string;
  durationMinutes: number;
  label: string;
}

/** Date/time change for `[Reagendar]` (target must be free). */
export interface SchedulePatch {
  date: string;
  timeSlot: string;
}

/** A studio artist/staff member shown publicly (feature 012). */
export interface TeamMember {
  id: string; // UUID
  name: string;
  role: string;
  avatarUrl: string; // '' → placeholder
  bio: string;
  instagramHandle: string; // '' allowed, stored without a leading '@'
  isActive: boolean;
  createdAt: string; // ISO
}

/** Creation input — the `id` is generated by the data source (DB uuid / crypto.randomUUID). */
export interface NewTeamMemberInput {
  name: string;
  role: string;
  avatarUrl: string;
  bio: string;
  instagramHandle: string;
}

/** Managed public gallery photo (feature 016). */
export interface GalleryItemRecord {
  id: string;

  /** Optional; defaults to ""; empty renders no caption. */
  title: string;

  /** Optional free-form text; defaults to "". */
  category: string;

  /** REQUIRED, non-empty image URL (upload via the storage service). */
  imageUrl: string;

  /** Public visibility; only active items are listed publicly. */
  isActive: boolean;

  createdAt: string;
}

/** Creation input — `id`/`createdAt` generated, `isActive` forced true by the data source. */
export interface NewGalleryItemInput {
  title?: string;
  category?: string;
  imageUrl: string;
}

/** Typed application error thrown by the data layer (never raw/unexpected values). */
export class DataError extends Error {
  constructor(message: string) {
    super(message);
    this.name = "DataError";
  }
}

/** The ONLY data-access surface components are allowed to use. */
export interface DataStore {
  readonly mode: DataMode;
  listServices(input?: { includeInactive?: boolean }): Promise<PiercingService[]>;
  createService(input: NewServiceInput): Promise<PiercingService>;
  updateService(
    id: string,
    patch: Partial<NewServiceInput> & { active?: boolean },
  ): Promise<PiercingService>;
  deleteService(id: string): Promise<void>;
  listProducts(input: { includeUnpublished: boolean }): Promise<ProductRecord[]>;
  createProduct(input: NewProductInput): Promise<ProductRecord>;
  updateProduct(
    id: string,
    patch: Partial<Pick<ProductRecord, "stock" | "published">>,
  ): Promise<ProductRecord>;
  listBookings(input?: { date?: string }): Promise<Booking[]>;
  createBooking(input: NewBookingInput): Promise<Booking>;
  updateBookingStatus(id: string, status: BookingStatus): Promise<Booking>;
  getBookedSlots(date: string): Promise<string[]>;
  /** Manual unavailability blocks (feature 006). */
  listBlocks(input?: { date?: string }): Promise<TimeBlock[]>;
  createBlock(input: NewBlockInput): Promise<TimeBlock>;
  deleteBlock(id: string): Promise<void>;
  /** Moves a booking to a new exclusive date/time slot (feature 006). */
  updateBookingSchedule(id: string, patch: SchedulePatch): Promise<Booking>;
  /** timeSlot values manually blocked for a date (public availability). */
  getBlockedSlots(date: string): Promise<string[]>;
  /** Team / staff roster (feature 012). Without options → active only (public). */
  listTeamMembers(input?: { includeInactive?: boolean }): Promise<TeamMember[]>;
  createTeamMember(input: NewTeamMemberInput): Promise<TeamMember>;
  updateTeamMember(
    id: string,
    patch: Partial<NewTeamMemberInput> & { isActive?: boolean },
  ): Promise<TeamMember>;
  deleteTeamMember(id: string): Promise<void>;
  /** Managed public gallery (feature 016). Public list returns only active photos. */
  listGalleryItems(input?: { includeInactive?: boolean }): Promise<GalleryItemRecord[]>;
  createGalleryItem(input: NewGalleryItemInput): Promise<GalleryItemRecord>;
  toggleGalleryItemActive(id: string): Promise<GalleryItemRecord>;
  deleteGalleryItem(id: string): Promise<void>;
}